export const FETCH_POSTS = 'FETCH_POSTS'
export const CHANGE_PAGE_POSTS = 'CHANGE_PAGE_POSTS'
export const FETCH_BY_COUNTRY_POSTS = 'FETCH_BY_COUNTRY_POSTS'
export const FETCH_BY_CATEGORY_POSTS = 'FETCH_BY_CATEGORY_POSTS'